# Generated by Django 2.0.6 on 2018-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
